stages:

  # Stage 1: Data Ingestion
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/stage_01_data_ingestion.py  # Command to run the data ingestion script
    deps:
      - src/cnnClassifier/pipeline/stage_01_data_ingestion.py  # Dependency: data ingestion script
      - config/config.yaml                                     # Dependency: configuration file
    outs:
      - artifacts/data_ingestion/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone  # Output: dataset directory after ingestion

  # Stage 2: Prepare Base Model
  prepare_base_model:
    cmd: python src/cnnClassifier/pipeline/stage_02_prepare_base_model.py  # Command to run the base model preparation script
    deps:
      - src/cnnClassifier/pipeline/stage_02_prepare_base_model.py  # Dependency: base model preparation script
      - config/config.yaml                                         # Dependency: configuration file
    params:
      - IMAGE_SIZE           # Model input image dimensions
      - INCLUDE_TOP          # Whether to include the fully connected layers
      - CLASSES              # Number of output classes
      - WEIGHTS              # Pre-trained weights to use
      - LEARNING_RATE        # Learning rate for model training
    outs:
      - artifacts/prepare_base_model  # Output: directory for prepared base model

  # Stage 3: Model Training
  training:
    cmd: python src/cnnClassifier/pipeline/stage_03_model_training.py  # Command to run the model training script
    deps:
      - src/cnnClassifier/pipeline/stage_03_model_training.py  # Dependency: model training script
      - config/config.yaml                                    # Dependency: configuration file
      - artifacts/data_ingestion/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone  # Dependency: ingested dataset
      - artifacts/prepare_base_model                          # Dependency: prepared base model
    params:
      - IMAGE_SIZE           # Model input image dimensions
      - EPOCHS               # Number of training epochs
      - BATCH_SIZE           # Batch size for training
      - AUGMENTATION         # Enable/disable data augmentation
    outs:
      - artifacts/training/model.h5  # Output: trained model file

  # Stage 4: Model Evaluation
  evaluation:
    cmd: python src/cnnClassifier/pipeline/stage_04_model_evaluation.py  # Command to run the model evaluation script
    deps:
      - src/cnnClassifier/pipeline/stage_04_model_evaluation.py  # Dependency: model evaluation script
      - config/config.yaml                                      # Dependency: configuration file
      - artifacts/data_ingestion/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone  # Dependency: ingested dataset
      - artifacts/training/model.h5                             # Dependency: trained model file
    params:
      - IMAGE_SIZE           # Model input image dimensions
      - BATCH_SIZE           # Batch size for evaluation
    metrics:
      - scores.json:          # Evaluation metrics output file
          cache: false        # Do not cache metrics for this file
